settings:
  title: 'System Status'
  url: 'https://status.syvita.org' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Systems Online'
  notAllmonitorsOperational: 'Mostly'
  monitorLabelOperational: 'Online'
  monitorLabelNotOperational: 'Offline'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: mainnet-syvita # unique identifier
    name: Mainnet API
    description: 'Global Stacks mainnet API nodes' # default=empty
    url: 'https://mainnet.syvita.org/extended/v1/status' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: syvita-org
    name: Syvita Home
    description: 'Welcome to the Guild!'
    url: 'https://syvita.org'
    method: GET
    expectStatus: 200

  - id: explorer
    name: Syvita Explorer
    url: 'https://explorer.syvita.org'
    method: GET
    expectStatus: 200
  - id: synapse
    name: Synapse
    url: 'https://synapse.syvita.org'
    expectStatus: 200
    followRedirect: true
